package:
  name: conda-which
  version: 0.1

source:
  path: ../

build:
  script: $PYTHON -m pip install --no-deps .

requirements:
  host:
    - python >=3.7

  run:
    - conda
    - python >=3.7

about:
  home: https://github.com/droumis/conda-which
  license: BSD-3-Clause
  summary: "Which environments have <package> installed?"
